/*
    Campus Lost-and-Found Database
    File: 01_schema.sql

    Run this file in a dedicated PostgreSQL database.
    It removes and recreates only the six tables used by this project.
*/

BEGIN;

DROP TABLE IF EXISTS claims;
DROP TABLE IF EXISTS claimants;
DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS campus_locations;
DROP TABLE IF EXISTS item_categories;

CREATE TABLE item_categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(80) NOT NULL UNIQUE,

    CONSTRAINT category_name_not_blank
        CHECK (BTRIM(category_name) <> '')
);

CREATE TABLE campus_locations (
    location_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name VARCHAR(120) NOT NULL UNIQUE,
    building_name VARCHAR(120),
    floor_label VARCHAR(40),
    location_description VARCHAR(300),

    CONSTRAINT location_name_not_blank
        CHECK (BTRIM(location_name) <> ''),
    CONSTRAINT building_name_not_blank
        CHECK (building_name IS NULL OR BTRIM(building_name) <> ''),
    CONSTRAINT floor_label_not_blank
        CHECK (floor_label IS NULL OR BTRIM(floor_label) <> '')
);

CREATE TABLE items (
    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL,
    item_name VARCHAR(120) NOT NULL,
    primary_color VARCHAR(50) NOT NULL,
    brand VARCHAR(80),
    public_description VARCHAR(500),
    distinguishing_feature VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_items_category
        FOREIGN KEY (category_id)
        REFERENCES item_categories (category_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT item_name_not_blank
        CHECK (BTRIM(item_name) <> ''),
    CONSTRAINT primary_color_not_blank
        CHECK (BTRIM(primary_color) <> ''),
    CONSTRAINT brand_not_blank
        CHECK (brand IS NULL OR BTRIM(brand) <> '')
);

CREATE TABLE reports (
    report_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL UNIQUE,
    location_id INTEGER NOT NULL,
    report_type VARCHAR(5) NOT NULL,
    incident_date DATE NOT NULL,
    reported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    report_status VARCHAR(10) NOT NULL DEFAULT 'OPEN',
    report_notes VARCHAR(500),

    CONSTRAINT fk_reports_item
        FOREIGN KEY (item_id)
        REFERENCES items (item_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_reports_location
        FOREIGN KEY (location_id)
        REFERENCES campus_locations (location_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT valid_report_type
        CHECK (report_type IN ('LOST', 'FOUND')),
    CONSTRAINT valid_report_status
        CHECK (report_status IN ('OPEN', 'MATCHED', 'RESOLVED', 'CLOSED')),
    CONSTRAINT incident_not_after_report
        CHECK (incident_date <= reported_at::DATE),
    CONSTRAINT report_notes_not_blank
        CHECK (report_notes IS NULL OR BTRIM(report_notes) <> ''),

    /*
        This candidate key supports the composite foreign key in claims.
        Together with claims.found_report_type = 'FOUND', it prevents a claim
        from pointing to a LOST report.
    */
    CONSTRAINT uq_reports_id_type
        UNIQUE (report_id, report_type)
);

CREATE TABLE claimants (
    claimant_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claimant_name VARCHAR(120) NOT NULL,
    institutional_id VARCHAR(40) NOT NULL UNIQUE,
    contact_email VARCHAR(160) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT claimant_name_not_blank
        CHECK (BTRIM(claimant_name) <> ''),
    CONSTRAINT institutional_id_not_blank
        CHECK (BTRIM(institutional_id) <> ''),
    CONSTRAINT contact_email_not_blank
        CHECK (BTRIM(contact_email) <> ''),
    CONSTRAINT contact_email_has_at_sign
        CHECK (POSITION('@' IN contact_email) > 1)
);

CREATE TABLE claims (
    claim_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    found_report_id INTEGER NOT NULL,

    /*
        Users do not need to enter this column. Its fixed value allows the
        composite foreign key to prove that found_report_id is a FOUND report.
    */
    found_report_type VARCHAR(5) NOT NULL DEFAULT 'FOUND',
    claimant_id INTEGER NOT NULL,
    filed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    claim_status VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    decided_at TIMESTAMPTZ,
    verification_notes VARCHAR(500),
    returned_at TIMESTAMPTZ,

    CONSTRAINT fk_claims_found_report
        FOREIGN KEY (found_report_id, found_report_type)
        REFERENCES reports (report_id, report_type)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_claims_claimant
        FOREIGN KEY (claimant_id)
        REFERENCES claimants (claimant_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT found_report_type_must_be_found
        CHECK (found_report_type = 'FOUND'),
    CONSTRAINT valid_claim_status
        CHECK (
            claim_status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')
        ),
    CONSTRAINT decision_matches_status
        CHECK (
            (claim_status = 'PENDING' AND decided_at IS NULL)
            OR
            (
                claim_status IN ('APPROVED', 'REJECTED', 'CANCELLED')
                AND decided_at IS NOT NULL
            )
        ),
    CONSTRAINT decision_not_before_filing
        CHECK (decided_at IS NULL OR decided_at >= filed_at),
    CONSTRAINT return_requires_approval
        CHECK (
            returned_at IS NULL
            OR
            (
                claim_status = 'APPROVED'
                AND decided_at IS NOT NULL
                AND returned_at >= decided_at
            )
        ),
    CONSTRAINT one_claim_per_person_per_report
        UNIQUE (found_report_id, claimant_id)
);

/*
    Several people may claim one found item, but PostgreSQL permits only one
    APPROVED claim for that report.
*/
CREATE UNIQUE INDEX uq_one_approved_claim_per_found_report
    ON claims (found_report_id)
    WHERE claim_status = 'APPROVED';

COMMIT;

